spring:
  application:
    name: lotto

  datasource:
    url: ${LOTTO_DB_URL}
    username: ${LOTTO_DB_USERNAME}
    password: ${LOTTO_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.company.lotto.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
